### PR TITLE
With best-effort compilation, ogmarkup becomes total

### PR DESCRIPTION
**Pull request by Ikyushii**
This is a quick proposal. From my point of view and now that we have a best-effort compilation with errors that are embedded within the output, if ogmarkup fails then we have a bug. Therefore, we should assume ogmarkup is a total functions that always returns something.

### CODE REVIEW

**Comment by lgeorget** [comment]
After conflict resolution, we're almost there but the HTML generated in case of errors is invalid. Could this be a problem ?

**Comment by Ikyushii** [comment]
Invalid how so?

**Comment by lgeorget** [comment]
There is text outside of <p></p>.

**Comment by Ikyushii** [comment]
Oh. Well, we have to blaim the configuration for that, I suppose.

**Pull request merged**
