### PR TITLE
Complete the documentation of the library

### PR DESCRIPTION
**Pull request by Ikyushii**

### CODE REVIEW

**Comment by Ikyushii** [comment]
Eh @lgeorget, I think I am done here. I would really appreciate if you could find some time to have a look before the merge.

**Comment by Ikyushii** [comment]
The [online documentation](http://ogma-project.github.io/ogmarkup/) have been updated to ease the work of potential reviewers.

**Comment by lgeorget** [comment]
The potential reviewers appreciate indeed. :+1: :-)

I review this tonight.

**Comment by Ikyushii** [comment]
Thanks! You can commit your modifications and push directly to my branch if you please.

**Comment by lgeorget** [comment]
Done. We wait for Travis and then we can merge.

**Comment by Ikyushii** [comment]
All good for me!

**Pull request merged**
